// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  advanceAmount = 75;
  selectedBox = 1;
  tipOptions = [
    {
      amount: 5,
      trees: 5
    },
    {
      amount: 10,
      trees: 10
    },
    {
      amount: 15,
      trees: 30
    },
    {
      amount: 20,
      trees: 40
    }
  ];

  onSelectOption(option: number) {
    this.selectedBox = option;
  }

  onSubmit() {
    alert('Thank you for your tip!');
  }
}

<div class="App">
  <div class="Top">
    <h1 class="Header">I sent you the money!</h1>
    <p class="SubHeader">
      Your optional tip helps us stay in business. We also plant a tree for every % tip.
    </p>
    <img src="assets/dave.png" class="Dave" />
    <img src="assets/background.png" class="Background" />
  </div>

  <div class="Tips">
      <div class="Box" [ngClass]="{'SelectedBox': selectedBox === 1}" (click)="onSelectOption(1)">
      <span class="BoxTitle">No tip</span>
    </div>
    <div class="Box" [ngClass]="{'SelectedBox': selectedBox === 2}" (click)="onSelectOption(2)">
      <p class="BoxTitle">{{tipOptions[0].trees}}</p>
      <span class="BoxSubtitle">Trees planted</span>
      <p class="BoxSubtitle">{{tipOptions[0].amount}}%</p>
    </div>
        <div class="Box" [ngClass]="{'SelectedBox': selectedBox === 3}" (click)="onSelectOption(3)">
      <p class="BoxTitle">{{tipOptions[1].trees}}</p>
      <span class="BoxSubtitle">Trees planted</span>
      <p class="BoxSubtitle">{{tipOptions[1].amount}}%</p>
    </div>
        <div class="Box" [ngClass]="{'SelectedBox': selectedBox === 4}" (click)="onSelectOption(4)">
      <p class="BoxTitle">{{tipOptions[2].trees}}</p>
      <span class="BoxSubtitle">Trees planted</span>
      <p class="BoxSubtitle">{{tipOptions[2].amount}}%</p>
    </div>
        <div class="Box" [ngClass]="{'SelectedBox': selectedBox === 5}" (click)="onSelectOption(5)">
      <p class="BoxTitle">{{tipOptions[3].trees}}</p>
      <span class="BoxSubtitle">Trees planted</span>
      <p class="BoxSubtitle">{{tipOptions[3].amount}}%</p>
    </div>
  </div>
  <p class="Pay">Pay nothing now. Collected on payback.</p>
  <button class="Button" (click)="onSubmit()">
    <span>Tip</span>
  </button>
</div>

// react/src/App.js
import React from "react";
import background from "./background.png";
import dave from "./dave.png";
import "./App.css";

var classNames = require("classnames");

const ADVANCE_AMOUNT = 75;
const TIPS = [
  {
    amount: 5,
    trees: 5
  },
  {
    amount: 10,
    trees: 10
  },
  {
    amount: 15,
    trees: 30
  },
  {
    amount: 20,
    trees: 40
  }
];


class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      tipOptions: [],
      selectedBoxIndex: 1
    };
  }

  componentDidMount() {
    this.setState({ tipOptions: TIPS });
  }

  renderTips = () => {
    if (this.state.tipOptions.length) {
      return (
        <div className="Tips">
          <div
            className={classNames("Box", { SelectedBox: this.state.selectedBoxIndex === 1 })}
            onClick={() => this.setState({ selectedBoxIndex: 1 })}
          >
            <span className="BoxTitle">No tip</span>
          </div>
          <div
            className={classNames("Box", { SelectedBox: this.state.selectedBoxIndex === 2 })}
            onClick={() => this.setState({ selectedBoxIndex: 2 })}
          >
            <p className="BoxTitle">{this.state.tipOptions[0].trees}</p>
            <span className="BoxSubtitle">Trees planted</span>
            <p className="BoxSubtitle">{`${this.state.tipOptions[0].amount}%`}</p>
          </div>
          <div
            className={classNames("Box", { SelectedBox: this.state.selectedBoxIndex === 3 })}
            onClick={() => this.setState({ selectedBoxIndex: 3 })}
          >
            <p className="BoxTitle">{this.state.tipOptions[1].trees}</p>
            <span className="BoxSubtitle">Trees planted</span>
            <p className="BoxSubtitle">{`${this.state.tipOptions[1].amount}%`}</p>
          </div>
          <div
            className={classNames("Box", { SelectedBox: this.state.selectedBoxIndex === 4 })}
            onClick={() => this.setState({ selectedBoxIndex: 4 })}
          >
            <p className="BoxTitle">{this.state.tipOptions[2].trees}</p>
            <span className="BoxSubtitle">Trees planted</span>
            <p className="BoxSubtitle">{`${this.state.tipOptions[2].amount}%`}</p>
          </div>
          <div
            className={classNames("Box", { SelectedBox: this.state.selectedBoxIndex === 5 })}
            onClick={() => this.setState({ selectedBoxIndex: 5 })}
          >
            <p className="BoxTitle">{this.state.tipOptions[3].trees}</p>
            <span className="BoxSubtitle">Trees planted</span>
            <p className="BoxSubtitle">{`${this.state.tipOptions[3].amount}%`}</p>
          </div>
        </div>
      );
    }
  };

  handleClick = () => {
    alert("Thank you for your tip!");
  };

  render() {
    return (
      <div className="App">
        <div className="Top">
          <h1 className="Header">I sent you the money!</h1>
          <p className="SubHeader">
            Your optional tip helps us stay in business. We also plant a tree for every % tip.
          </p>
          <img src={dave} className="Dave" />
          <img src={background} className="Background" />
        </div>
        {this.renderTips()}
        <p className="Pay">Pay nothing now. Collected on payback.</p>
        <button className="Button" onClick={this.handleClick}>
          <span>Tip</span>
        </button>
      </div>
    );
  }
}

export default App;
